trigger:
  branches:
    include:
      - main  # Replace with the branch you want to trigger the pipeline on

pool:
  vmImage: 'ubuntu-latest'  # Choose an appropriate agent image

stages:
- stage: Dev
  displayName: 'Developement'
  jobs:
    - job: Build
      steps:
      - script: |
          az login --tenant ramsumanthoutlook.onmicrosoft.com
          docker login deamon.azurecr.io -u deamon -p 7CrYf4nosXrPZn2fwztHE1jUdj6fOgM+9Y6PxwpUh2+ACRAzpAjH
          docker pull nginx
          docker tag nginx deamon.azurecr.io/demo/nginxv4
          docker push deamon.azurecr.io/demo/nginxv4

- stage: Prod
  displayName: 'Production'
  jobs:
    - job: Build
      steps:
      - script: |
          az login --tenant ramsumanthoutlook.onmicrosoft.com
          docker login deamon.azurecr.io -u deamon -p 7CrYf4nosXrPZn2fwztHE1jUdj6fOgM+9Y6PxwpUh2+ACRAzpAjH
          docker pull nginx
          docker tag nginx deamon.azurecr.io/prod/nginxv1
          docker push deamon.azurecr.io/prod/nginxv1
